name: Durchkompilieren

on:
  push:
    branches: [ "master" ]

jobs:
  job-fatjar:
    runs-on: ubuntu-latest
    steps:
    - name: Git-Repo auschecken
      uses: actions/checkout@v4
    - name: JDK einrichten
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: FatJar-Datei mit Maven bauen
      run: ./mvnw --batch-mode clean package
    # NICHT hochladen
